site_name: What the Phage
nav:
    - Home: index.md
    - Installation:
        - Quick Installation: installation/quick_installation.md
        - Nextflow: installation/nextflow.md
        - Environment:
          - Local/Cluster: installation/Environment/environment.md 
        - Engine:
          - Docker: installation/Engine/docker.md
          - Singularity: installation/Engine/singularity.md 
        - test WtP: installation/test.md
    - Workflow execution:
          - Overview: Workflow-execution/Overview.md
          - Commands: Workflow-execution/commands.md
          - Testrun: Workflow-execution/results.md
    - Troubleshooting: 
          - Troubleshooting: troubleshooting.md
theme: 
  name: material
  highlightjs: true
  hljs_languages:
      - yaml
      - rust
      - bash
      - shell
      - nextflow
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: orange
    accent: purple
  font:
    text: Roboto
    code: Roboto Mono
