site_name: What the Phage
nav:
    - Home: index.md
    - Installation:
        - Quick Installation: installation/quick_installation.md
        - Nextflow: installation/nextflow.md
        - Environment:
          - Local/Cluster: installation/Environment/conda.md 
        - Engine:
          - Docker: installation/Engine/docker.md
          - Singularity: installation/Engine/singularity.md 
    - Test WtP: test.md
    - Workflow execution:
        - WtP commands: Workflow-execution/command.md
        - Explaining the Results: Workflow-execution/results.md
    - Troubleshooting: troubleshooting.md
theme: readthedocs
