site_name: What the Phage
nav:
    - Home: index.md
    - Installation:
        - Quick Installation: installation/quick_installation.md
        - Nextflow: installation/nextflow.md
        - Environment:
          - Local/Cluster: installation/Environment/environment.md 
        - Engine:
          - Docker: installation/Engine/docker.md
          - Singularity: installation/Engine/singularity.md 
    - Test WtP: test.md
    - Workflow execution:
          - Overview: Workflow-execution/Overview.md
          - Commands: Workflow-execution/commands.md
          - Explaining the Results: Workflow-execution/results.md
    - Troubleshooting: troubleshooting.md
theme: 
  name: readthedocs  
  collapse_navigation: false
