site_name: What the Phage
nav:
    - Home: index.md
    - Get Started:  get_started.md
    - Installation:
        - Nextflow: installation/nextflow.md
        - Docker: installation/docker.md
        - Singularity: installation/singularity.md
        - Quick Installation: installation/quick_installation.md
    - Test the Workflow: test.md
    - Execution of WtP: command.md
    - Example Results: results.md
    - About: about.md
theme:
    name: 'material'
    custom_dir: 'theme'
    palette:
    primary: 'green'
    accent: 'light green'
      
    extra_css:
    - stylesheets/dark_theme.css
    - stylesheets/codehilite.css
highlightjs: true
hljs_languages:
    - yaml
    - rust
    - shell
    - docker
    - nextflow
   # extra_css:
   #     - stylesheets/dark_theme.css
   #     - stylesheets/codehilite.css

# # Documentation and theme
# theme:
#     name: 'material'
#     custom_dir: 'theme'
#     palette:
#       primary: 'green'
#       accent: 'light green'
#   extra_css:
#         - stylesheets/dark_theme.css
#         - stylesheets/codehilite.css



#         site_name: What the Phage
#         nav:
#             - Home: index.md
#             - Get Started:  get_started.md
#             - Installation:
#                 - Nextflow: installation/nextflow.md
#                 - Docker: installation/docker.md
#                 - Singularity: installation/singularity.md
#                 - Quick Installation: installation/quick_installation.md
#             - Test the Workflow: test.md
#             - Execution of WtP: command.md
#             - Example Results: results.md
#             - About: about.md
#         # theme: readthedocs
#         highlightjs: true
#         hljs_languages:
#             - yaml
#             - rust
#             - shell
#             - docker
#             - nextflow