site_name: What the Phage
nav:
    - Home: index.md
    - Get Started:  get_started.md
    - Installation:
        - Nextflow: installation/nextflow.md
        - Docker: installation/docker.md
        - Singularity: installation/singularity.md
        - Conda: installation/conda.md
        - Quick Installation: installation/quick_installation.md
    - Test the Workflow: test.md
    - Running WtP: command.md
    - Example Results: results.md
    - Troubleshooting and common errors: troubleshooting.md
    - About: about.md
theme: 
  palette:
    scheme: default
    primary: blue grey
    accent: orange
  font:
    text: Roboto
    code: Roboto Mono
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - shell

#copyright: ©2020 nanozoo & mike