name: ci
on:
  push:
    branches:
      - master
jobs:
  container:
    runs-on: ubuntu-latest
    container: minidocks/mkdocs:1.0
    steps:
      - uses: actions/checkout@v2
      - run: mkdocs gh-deploy --force
